version: '3.8'
services:
  redis:
    image: redis
    # container_name: redis
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - ./Db:/data
    networks:
      - globomantics
  api:
    image: sswietoniowski/globomantics-api
    # container_name: globomantics-api
    restart: on-failure
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - redis
    networks:
      - globomantics
  client:
    image: sswietoniowski/globomantics-client
    # container_name: globomantics-client
    restart: on-failure
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - api
    networks:
      - globomantics
networks:
  globomantics:
    driver: bridge
